### PR TITLE
Create DE.json

### PR DESCRIPTION
**Pull request by hEvaDer**

### CODE REVIEW

**Comment by xMrVizzy** [comment]
@hEvaDer thank you so much!!!!

**Comment by hEvaDer** [comment]
No Problem man...;)

**Comment by hEvaDer** [comment]
it would be nice if you add my username next to german in the language section?!

**Comment by xMrVizzy** [comment]
Yeah, it awesome, but it is not estetic look in menu, i will create a Credits section with all who help in localization and other things!!!

**Comment by hEvaDer** [comment]
Okay perfect! ;)

**Comment by xMrVizzy** [comment]
Made, you can update shortcuts, to check out Credits feature, and also please add yourself in credits.

**Pull request merged**
